name: Build Image and Push to Quay

on: push

jobs:
  Security:
    name: Security Pipeline
    uses: uc-cdis/.github/.github/workflows/securitypipeline.yaml@master
    with:
      python-poetry: 'false'
    secrets: inherit # pragma: allowlist-secret
